version: "3.9"

services:
  db:
    restart: on-failure
    image: postgres:13-buster
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
  api:
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:3000"
  web:
    restart: on-failure
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - db
      - api
    ports:
      - "8100:3000"